kind: Service
apiVersion: v1
metadata:
  name: apache-server-service
spec:
  selector:
    app: apache-server
  ports:
    - protocol: "TCP"
      # accessible inside cluster
      port: 8081
      # inside the pod
      targetPort: 8080
      # accessible outside cluster
      nodePort: 30002
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache-server-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: apache-server
    spec:
      containers:
        - name: apache-server
          image: ebisong.net/apache_server
          ports:
            - containerPort: 8080