kind: Service
apiVersion: v1
metadata:
  name: nginx-server-service
spec:
  selector:
    app: nginx-server
  ports:
    - protocol: "TCP"
      # accessible inside cluster
      port: 8081
      # inside the pod
      targetPort: 8080
      # accessible outside cluster
      nodePort: 30002
  type: LoadBalancer

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-server-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
        - name: nginx-server
          image: ekababisong/ebisong-nginx-server
          ports:
            - containerPort: 8080